parameters:
#    edeli_site.example.class: Edeli\SiteBundle\Example

services:
#    edeli_site.example:
#        class: %edeli_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
