<?php

namespace Prenomea\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtymologyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtymologyRepository extends EntityRepository
{
}
