<?php

namespace Prenomea\SiteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PrenomRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrenomRepository extends EntityRepository
{
}
